
const rooms={
app:{title:'The front desk',hides:'App startup, connecting services and responding to shortcuts. This is a coordination point rather than an isolated feature.',crosses:'Before starting an action it checks other activities, such as recording, screenshots and notes. Changing which actions may run together can affect these checks.',evidence:[['AppDelegate.swift:21–45','Creates the services and loads settings.'],['AppDelegate.swift:142–235','Recording and screenshot commands check the busy state of other features.']]},
settings:{title:'Remember preferences',hides:'Where settings live, reading and writing JSON, migration from an old location, defaults and repairs. Callers mainly load, read or update settings.',crosses:'Other features still know the setting names they use. This clear boundary describes storage; it does not mean the entire settings interface is isolated.',evidence:[['SettingsStore.swift:50–100','load() and update() handle migration, normalization and persistence.'],['SettingsStore.swift:104–126','Disk reading, directory creation and atomic writing are private.']]},
capture:{title:'Get the picture',hides:'Screen capture, image preparation and handing a capture into the workflow. The caller can request an area or full-screen screenshot.',crosses:'It sets up the workflow with an image, its pending file write, settings and supporting services. Image-conversion helpers are also used outside this area.',evidence:[['ScreenshotService.swift:71–131','captureArea() and captureFullScreen() are the main capture commands.'],['ScreenshotService.swift:167–184','Constructs the workflow, supplies its dependencies and calls start().']]},
workflow:{title:'Rename, note & save',hides:'A caller starts a workflow and gets a completion callback. Panel transitions, backups, persistence waits and final file actions are coordinated inside.',crosses:'For a note-only save on a reopened image, the workflow creates the editor’s drawing canvas directly. It must understand the saved drawing state and clean base picture.',evidence:[['ScreenshotService.swift:167–184','Workflow setup followed by onFinish and start().'],['ScreenshotWorkflowController.swift:332–391','Opens the editor and receives its result.'],['ScreenshotWorkflowController.swift:839–848','annotatedBaseImage() constructs EditorCanvasView to redraw saved annotations.']]},
editing:{title:'Draw on the picture',hides:'Drawing objects, undo history, selection and hit-testing mostly stay inside the canvas. Other code can request a composite image or editable state.',crosses:'The canvas also speaks the window’s language: save, close, zoom and color-picker commands. Final save/copy/delete choices exist in two definitions and are translated by the editor window.',evidence:[['EditorCanvasView.swift:28–54','FinalActionCommand and KeyCommand include both drawing and window actions.'],['EditorWindowController.swift:36','The editor uses a final-action type owned by the screenshot workflow.'],['EditorWindowController.swift:700–714','Manually maps the canvas final actions to the workflow final actions.']]},
recording:{title:'Record a video',hides:'The recording session, starting and stopping, display monitoring and finishing the video file. Other code uses start/stop, state and callbacks.',crosses:'The front desk decides when recording may start alongside other features. A separate video-rename controller handles the file after it is saved.',evidence:[['ScreenRecordingService.swift:39–55','Exposes state, elapsed time and a saved-recording callback.'],['ScreenRecordingService.swift:92–127','High-level start and stop controls.'],['AppDelegate.swift:169–181','Opens a separate rename flow after recording.']]},
scratchpad:{title:'Write a note',hides:'Opening a standalone note panel and turning its text into a note file or clipboard content.',crosses:'The app coordinates when it can open, and it uses shared note-panel and clipboard code. A separate entry point is established; its depth has not received the same focused review as settings or PNG handling.',evidence:[['AppDelegate.swift:37','Creates ScratchpadService with the clipboard service.'],['ScratchpadService.swift','Owns the standalone note flow and uses NotePanelController.']]},
metadata:{title:'Pack & unpack edit information',hides:'PNG chunks, embedded text, encoding and extracting saved editing information. Callers use embed and extract operations.',crosses:'Saving and reopening still choose which information belongs in the file. The PNG helper handles the format; it does not own the entire saving policy.',evidence:[['PNGMetadata.swift:25–138','Embedding and extraction hide the internal PNG format.'],['WorkflowImagePersistenceLogic.swift:31–41','Saving calls the embed operations.'],['WorkflowReopenMetadataLogic.swift:58–59','Reopening calls the extraction operations.']]},
helpers:{title:'Tools used by several rooms',hides:'Each tool handles a smaller job, such as a clipboard write, a backup or a filename collision. Their depth varies; small size alone is not a problem.',crosses:'This dashed area is a collection, not a shared gateway. Features call these tools directly. Settings UI and shortcut registration also have their own files outside the storage room.',evidence:[['ClipboardService.swift / BackupService.swift / UniqueFileURLLogic.swift','Separate reusable helpers, rather than a single shared service.'],['ScreenshotServiceCoreLogic.swift','Image conversion functions are used by capture, workflow and editing code.'],['SettingsWindowController.swift / HotKeyService.swift','Settings controls and shortcuts are separate from SettingsStore.']]}
};
const buttons=[...document.querySelectorAll('[data-room]')],detail=document.getElementById('detail');let selected;
buttons.forEach(button=>button.addEventListener('click',()=>{selected=button;buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const d=rooms[button.dataset.room];document.getElementById('detail-title').textContent=d.title;document.getElementById('hides').textContent=d.hides;document.getElementById('crosses').textContent=d.crosses;document.getElementById('source-details').open=false;const evidence=document.getElementById('evidence');evidence.replaceChildren(...d.evidence.map(([file,explanation])=>{const item=document.createElement('div'),code=document.createElement('code'),p=document.createElement('p');code.textContent='Sources/'+file;p.textContent=explanation;item.append(code,p);return item}));detail.hidden=false;detail.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}));
document.getElementById('close').addEventListener('click',()=>{detail.hidden=true;buttons.forEach(b=>b.setAttribute('aria-pressed','false'));selected?.focus()});
